/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for nf_nat_snmp_basic
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder nf_nat_snmp_basic_decoder;

extern int snmp_helper(void *, size_t, unsigned char, const void *, size_t);
extern int snmp_version(void *, size_t, unsigned char, const void *, size_t);

